### PR TITLE
Updating assets to include functions branding

### PR DESCRIPTION
**Pull request by btardif**
@lindydonna can you take a look?

### CODE REVIEW

**Comment by lindydonna** [comment]
@btardif It looks great!  Is it possible to lighten the surprised emoji a bit?  It makes the text at the bottom hard to read.

**Comment by lindydonna** [comment]
Actually, it looks like happy and neutral have the same issue. Is it an easy fix?

**Comment by btardif** [comment]
Yeah, I should be able to play with transparency, if you want to come take a look, it might be faster than iterating over revisions

**Comment by btardif** [comment]
@lindydonna new revision is up

**Pull request merged**
